# Importing the libararies 

In [2]:
import tensorflow as tf 
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
tf.__version__

'2.2.0'

# 1.  data preprocessing 

# importing the datasets

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[ : , 3 : -1].values
y = dataset.iloc[ : , -1 ].values


In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


# encoding the categorical data

## linear encoding for male and female 

In [6]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder 
from sklearn.compose import ColumnTransformer 
le = LabelEncoder()
x[ : , 2] = le.fit_transform(x[ : , 2])
print(y)

[1 0 1 ... 1 1 0]


## one hot encoding the geographical data i.e coutry 

In [7]:
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer( transformers = [('encoder' , OneHotEncoder() , [1]) ] , remainder = 'passthrough' )
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# spliting the dataset into test set and train set 

In [9]:
from sklearn.model_selection import train_test_split
train_x , test_x ,train_y , test_y = train_test_split(x , y , test_size = 0.2 , random_state = 0 )

# feature scaling ( note it is improtant to feature scale in deep learning incuding dummy variables or discrete variable )

In [10]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

# 2. Building the Artificial Neural network

# initializing the ann


In [11]:
ann = tf.keras.models.Sequential() # here the sequential means layers of sequence 

# initializing the input layer and first hidden layer 

In [12]:
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu')) # here the units is refferd to no of hidden neurons 

# initializing the second hidden layer 

In [13]:
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))

# initializing the output layer 

In [14]:
ann.add(tf.keras.layers.Dense(units = 1 , activation = 'sigmoid'))

# 3. Training the ANN

## compling the ann

In [18]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# training the ann on the training set 

In [19]:
ann.fit(train_x, train_y, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6519 - accuracy: 0.6589
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4957 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4684 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4456 - accuracy: 0.8016
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4214 - accuracy: 0.8163
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4012 - accuracy: 0.8290
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3867 - accuracy: 0.8371
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3764 - accuracy: 0.8418
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3690 - accuracy: 0.8465
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3641 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3348 - accuracy: 0.8633
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3351 - accuracy: 0.8639
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3350 - accuracy: 0.8641
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3352 - accuracy: 0.8624
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3344 - accuracy: 0.8627
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3350 - accuracy: 0.8643
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3343 - accuracy: 0.8629
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3346 - accuracy: 0.8644
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3352 - accuracy: 0.8631
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3348 - accuracy: 

# 4. predicting the result and evaluting the model 

## predicting the result of a single observation 

In [20]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


# predicting the test set results


In [21]:
y_pred = ann.predict(test_x)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1) , test_y.reshape(len(test_y),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# testing the accuracy 

In [22]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(test_y , y_pred)
accuracy = accuracy_score( test_y ,y_pred)
print(cm)
print(accuracy)

[[1519   76]
 [ 192  213]]
0.866
